artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/ffdd5e6f8464444c8df82bbd02595593/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755439077816
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: ffdd5e6f8464444c8df82bbd02595593
run_name: batch_analyze
source_name: ''
source_type: 4
source_version: ''
start_time: 1755438784460
status: 3
tags: []
user_id: saketh pc
