artifact_location: file:F:/GITHUB/finance-ll-complaints/0# leave blank for local;
  set to Azure ML later
creation_time: 1755433065144
experiment_id: '0'
last_update_time: 1755433065144
lifecycle_stage: active
name: Default
