artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/1a64db7fbea746d4bd256c216ee13158/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755436950573
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: 1a64db7fbea746d4bd256c216ee13158
run_name: batch_analyze
source_name: ''
source_type: 4
source_version: ''
start_time: 1755436710155
status: 3
tags: []
user_id: saketh pc
