artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/9e801bf1a8a848d084852e0097e550fc/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755436378319
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: 9e801bf1a8a848d084852e0097e550fc
run_name: analyse_single
source_name: ''
source_type: 4
source_version: ''
start_time: 1755436378140
status: 3
tags: []
user_id: saketh pc
