artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/db660b70d0db418abf174203b55f0635/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755438127992
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: db660b70d0db418abf174203b55f0635
run_name: batch_analyze
source_name: ''
source_type: 4
source_version: ''
start_time: 1755437880895
status: 3
tags: []
user_id: saketh pc
