artifact_location: file:F:/GITHUB/finance-ll-complaints/114496163058747961# leave
  blank for local; set to Azure ML later
creation_time: 1755433065165
experiment_id: '114496163058747961'
last_update_time: 1755433065165
lifecycle_stage: active
name: finance-llm
