artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/52a25c41fb364730bda36ff95bf02b40/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755440904070
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: 52a25c41fb364730bda36ff95bf02b40
run_name: analyse_single
source_name: ''
source_type: 4
source_version: ''
start_time: 1755440902242
status: 3
tags: []
user_id: saketh pc
