artifact_uri: file:F:/GITHUB/finance-ll-complaints/114496163058747961/ee65392d79cf41bd9cee55dca2cc04d5/artifacts#
  leave blank for local; set to Azure ML later
end_time: 1755440851112
entry_point_name: ''
experiment_id: '114496163058747961'
lifecycle_stage: active
run_id: ee65392d79cf41bd9cee55dca2cc04d5
run_name: analyse_single
source_name: ''
source_type: 4
source_version: ''
start_time: 1755440851042
status: 3
tags: []
user_id: saketh pc
